import React, { useEffect, useState } from 'react';
import Fade from '@mui/material/Fade';
import Divider from '@mui/material/Divider';
import "./learn-more.scss";

export default function LearnMore() {

  // Functions to get the headers from the page
  const getNestedHeadings = (headingElements) => {
    const nestedHeadings = [];

    headingElements.forEach((heading, index) => {
      const { innerText: title, id } = heading;

      if (heading.nodeName === "H2") {
        nestedHeadings.push({ id, title, items: [] });
      } else if (heading.nodeName === "H3" && nestedHeadings.length > 0) {
        nestedHeadings[nestedHeadings.length - 1].items.push({
          id,
          title,
        });
      }
    });

    return nestedHeadings;
  };
  const useHeadingsData = () => {
    const [nestedHeadings, setNestedHeadings] = useState([]);

    useEffect(() => {
      const headingElements = Array.from(
        document.querySelectorAll("h2, h3")
      );

      const newNestedHeadings = getNestedHeadings(headingElements);
      setNestedHeadings(newNestedHeadings);
    }, []);

    return { nestedHeadings };
  };

  // Table of contents component
  const Headings = ({ headings }) => (
    <ul className="lm-toc-list">
      {headings.map((heading) => (
        <li key={heading.id}>
          <span className="lm-list-item">
            <a
              href={`#${heading.id}`}
              onClick={(e) => {
                e.preventDefault();
                document.querySelector(`#${heading.id}`).scrollIntoView({
                  behavior: "smooth"
                });
              }}
              className="lm-toc-link"
            >
              {heading.title}
            </a>
            {heading.items.length > 0 && (
              <ul className="lm-toc-list-2">
                {heading.items.map((child) => (
                  <li key={child.id}>
                    <span className="lm-list-item">
                      <a
                        href={`#${child.id}`}
                        onClick={(e) => {
                          e.preventDefault();
                          document.querySelector(`#${child.id}`).scrollIntoView({
                            behavior: "smooth"
                          });
                        }}
                        className="lm-toc-link"
                      >
                        {child.title}
                      </a>
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </span>
        </li>
      ))}
    </ul>
  );
  const { nestedHeadings } = useHeadingsData();

  const fadeDuration = 300;
  const fadeOffset = 50;

  return (
    <>

      <div className="lm-wrapper">

        {/*Actual page */}
        <div className="lm-content">
          <div className="lm-text-wrapper">

            <Fade in={true} timeout={fadeDuration} style={{ transitionDelay: 1 * fadeOffset + 'ms' }}>
              <div>
                <Divider textAlign="left"><h2 id="section-1" className="lm-header">Basic notions</h2></Divider>
                <p>
                To fully understand how your data is stored and how it travels on the internet, it is necessary to explain some basic concepts: cookies, trackers, and fingerprints.
                </p>
                <h3 id="sub-section-1" className="lm-header">Cookies</h3>
                <p>
                While browsing the Internet, you may come across websites asking you to accept their cookies, without really understanding what they are. A cookie is a computer file generated by a website that saves data about your navigation. This file is stored on your browser, in your computer, and can contain a lot of information: the identifier of your customer account, the language chosen to navigate on the site, the consulted articles, etc.
                <br /><br />
                This data may be necessary for the proper functioning of the site, but some may be related to commercial activities only. From a legal point of view, the European Union protects its citizens by the GDPR: the General Data Protection Regulation. It is due to this regulation that you can choose which cookies you accept when browsing a site for the first time: only the necessary ones, or the other commercial ones as well.
                </p>
                <h3 id="sub-section-2" className="lm-header">Tracker</h3>
                <p>
                On each website, computer programs called "scripts" allow the proper functioning of web pages. They have access to a lot of data, including the user's cookies. Some protection exists to prevent scripts from accessing too much information and sending it to third parties. However, it is unfortunately still possible to extract / gain access to private data. This is called a tracker: a script whose main purpose is to collect private data about the user, and send it to third parties.
                </p>
                <h3 id="sub-section-3" className="lm-header">Fingerprinting</h3>
                <p>
                When you consult a web page, your browser sends a request to a server (a machine on which the site is located) to retrieve the page to be displayed. This request contains information about the user's browser and machine: time zone, browser version, operating system... With all this information, the site's server is able to build a profile of the user. Several different people can have the same profile if the information collected is identical, which prevents visited sites from recovering data from a specific person. In the case where a user has a unique profile, a visited site is able to clearly identify the user and therefore collect information about them.
                </p>
              </div>
            </Fade>

            <Fade in={true} timeout={fadeDuration} style={{ transitionDelay: 2 * fadeOffset + 'ms' }}>
              <div>
                <Divider textAlign="left"><h2 id="section-5" className="lm-header">Learn even more</h2></Divider>
                <p>
                In order to be transparent to our users, we will describe in the following paragraphs how our extension works.
                <br />
                A very important point of the extension is that everything happens locally, on your computer. No collected or analyzed information is sent to any entity, be it us or another. In fact, everything that happens in the extension stays on your computer.
                </p>
                <h3 id="sub-section-1" className="lm-header">Privacy risk percentage</h3>
                <p>
                When you visit a website, our extension determines a privacy risk percentage. This percentage can be used to determine the trustworthiness of a website, before giving it more personal information.  This percentage is the average of two other more precise percentages that we calculate: the cookie intrusiveness percentage and the tracking suspicion percentage.
                </p>
                <h3 id="sub-section-2" className="lm-header">Cookie intrusiveness percentage</h3>
                <p>
                In order to analyze the cookies generated by the site you are visiting, we collect them at each change of web page. They are first classified in 4 categories: strictly necessary, functional, statistical, commercial. This classification is obtained thanks to artificial intelligence algorithms, which we have taken from <a href="https://www.research-collection.ethz.ch/handle/20.500.11850/477333">the thesis of Dino Bollinger (ETH Zürich)</a>.
                <br /><br />
                Each cookie is then tied to a percentage based on two factors; its type and its duration of existence. 
                A strictly necessary cookie will have a percentage between 0% and 2%.
                A functional cookie will have a percentage between 2% and 35%.
                A statistical cookie will have between 35% and 65%.
                Finally a commercial cookie will have between 65% and 100%.
                The percentage will be closer to the lower or upper limit depending on whether its duration of existence is respectively closer to 1 day or 1 year. It turns out that many websites deposit cookies for more than 2 years.
                <br /><br />
                The final percentage is the largest percentage calculated.
                </p>
                {/*
                <h3 id="sub-section-3" className="lm-header">Tracking suspicion percentage</h3>
                <p>
                Todo
                </p>
                */}
                <h3 id="sub-section-4" className="lm-header">Deleting unecessary cookies</h3>
                <p>
                Once the cookies have been classified, we delete those that are not necessary for the proper functioning of the site, i.e. cookies for statistical and commercial purposes.
                </p>
                <h3 id="sub-section-5" className="lm-header">Deleting unused cookies</h3>
                <p>
                Privacy Keeper offers the possibility to delete unused cookies after a certain time. This duration can be set in the extension's options.
                Every time you go to a website, the extension updates the last date of use of cookies related to that web page.
                Every time you open your favorite browser, we delete all cookies that are older than the length of time you have chosen.
                </p>
              </div>
            </Fade>
          </div>
        </div>

        {/* Table of contents (sticky) */}
        <Fade in={true} timeout={fadeDuration} style={{ transitionDelay: 0 * fadeOffset + 'ms' }}>
          <div className="lm-toc">
            <nav aria-label="Table of contents">
              <div className="lm-toc-title">Table of Contents</div>
              <Headings headings={nestedHeadings} />
            </nav>
          </div>
        </Fade>

      </div>

    </>
  )
}